### ISSUE TITLE
`sem-version go XYZ` doesn't exit with error

### ISSUE THREAD

**Issue by lmb** [semaphoreci/toolbox#176]
See https://ebpf.semaphoreci.com/jobs/fbd289c5-060a-470f-aab0-9c933613642a

```
[13:44 01/09/2020]: Changing 'go' to version 1.15
Version not found. Please try another one.
​
[13:44 01/09/2020]: Switch successful.
```

**Comment by J3173** [comment]
We have the same problem with `sem-version java`:

```
sem-version java 9

[14:26 28/09/2020]: Changing 'java' to version 9
Please provide one of these values:
For java-7 use [1.7, 7]
For java-8 use [1.8, 8]
For java-11 use [11]

[14:26 28/09/2020]: Switch successful.
```

When switching to an invalid version it displays `Switch successful.` (it wasn't) and returns with return code 0 (success). I expected an error message ("Switch failed") and an non-zero return code.

**Comment by lmb** [comment]
This doesn't happen on latest `sem-version` anymore.
