### ISSUE TITLE
Python 3.11

### ISSUE THREAD

**Issue by caius** [semaphoreci/toolbox#383]
Python 3.11 was released in October 2022[^1] and I've been keeping an eye on the SemaphoreCI Changelog[^2] for it but haven't seen it listed yet.

Can we have it included in the standard environment please?

[^1]: https://www.python.org/downloads/release/python-3110/
[^2]: https://docs.semaphoreci.com/reference/semaphore-changelog/

**Comment by d-stefanovic** [comment]
Hello!

We will include Python 3.11 in our `focal` image on the next release (which is scheduled for next week).
I will update this ticket once it is released.

**Comment by caius** [comment]
This got added, many thanks!
