### ISSUE TITLE
checkout of PR does not retry and gives unhelpful error if git clone fails

### ISSUE THREAD

**Issue by mattbrictson** [semaphoreci/toolbox#386]
## Problem

When running `checkout` on a PR-triggered workflow, I get this unhelpful error:

```
bash: cd: myproj: No such file or directory
Revision: 53efa4c0626c054a9c305dfe40dc929a95f1142f not found .... Exiting
```

After doing some digging, it seems that the underlying `git clone` is failing, due to some intermittent network failures with GitHub. If I repeatedly run `git clone` directly, I sometimes see:

```
Cloning into 'myproj'...
kex_exchange_identification: read: Connection reset by peer
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

In other words, the root cause is apparently GitHub in this case (it is dropping the connection). However, Semaphore's `checkout` is hiding this error, because stderr for the `git clone` command is sent to `/dev/null`, like this:

https://github.com/semaphoreci/toolbox/blob/69e4ffa710b5ebaee4862bbfb15f1954a6698dd5/libcheckout#L208

Instead, `checkout` assumes that the clone succeeded (it doesn't check the exit status), and tries to change into the cloned directory, which doesn't exist. So the error the user sees in this case is:

```
bash: cd: myproj: No such file or directory
```

## Desired behavior

1. `checkout` should abort when a `git clone` operation fails, and show a helpful error message; ideally the stderr output of the underlying failed git command.
2. In addition, ideally `checkout` would provide a retry mechanism to gracefully recover from intermittent connection failures. Or the documentation should explain how `retry` and `checkout` can be used together (a naive `retry checkout` doesn't work).

**Comment by mattbrictson** [comment]
I'm not a bash expert by any means, and I don't know how to run the tests on this repo, but the PR seems to address this issue. Thanks!

**Comment by lucaspin** [comment]
@mattbrictson #387 and #407 were released as part of our latest toolbox version. Those PRs add retries on `git clone` and `git fetch` commands, which seem to be the main culprits for these intermittent failures. Please, let us know if you still see these issues, so we can further troubleshoot.

**Comment by mattbrictson** [comment]
Seems good to me! I'll reopen this issue if I run into the problem again. Thanks

**Comment by ThomasKwan-shopline** [comment]
Hi, I am still facing this issue at this moment, is the changes not updated or I need some new setting on my pipeline?

**Comment by lucianoliberti** [comment]
@ThomasKwan-shopline thanks for reporting it! We'll take a look and report back

**Comment by hamir-suspect** [comment]
Hello @ThomasKwan-shopline, the changes were released and are present on all semaphore machine types, what issues are you facing? Could you provide output of the `checkout` and open up a new issue with the explanation?
