### ISSUE TITLE
Libcheout doesn't set the branch

### ISSUE THREAD

**Issue by shiroyasha** [semaphoreci/toolbox#7]

**Comment by bmarkons** [comment]
Here's the screenshot:
https://d.pr/i/gG8RUo

**Comment by shiroyasha** [comment]
@bmarkons @darkofabijan what is the state of the issue, can we close it?

**Comment by bmarkons** [comment]
Yes, sorry for not closing it with https://github.com/semaphoreci/toolbox/pull/8
